# Generated by Django 4.2.30 on 2026-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_board_standard_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacecustomfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('paragraph', 'Paragraph'), ('date', 'Date'), ('number', 'Number'), ('datetime', 'Date and time'), ('categories', 'Categories'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('member', 'Member'), ('multi_select', 'Multi select'), ('url', 'URL')], max_length=32),
        ),
    ]
