# Generated by Django 4.2.30 on 2026-06-14 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0171_client360_finops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchembedding',
            name='entity_type',
            field=models.CharField(choices=[('issue', 'Issue'), ('page', 'Page'), ('comment', 'Comment'), ('playbook', 'Playbook'), ('client360_snapshot', 'Client360 snapshot')], max_length=32),
        ),
        migrations.CreateModel(
            name='WorkspaceClient360WeeklyBriefing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content_md', models.TextField(blank=True, default='')),
                ('facts_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('blocked', 'Blocked')], default='draft', max_length=16)),
                ('requires_review', models.BooleanField(default=True)),
                ('qa_issues', models.JSONField(blank=True, default=list)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_weekly_briefings', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_weekly_briefings',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceClient360ScenarioPlaybook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scenario_key', models.CharField(max_length=64)),
                ('playbook_code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('markdown', models.TextField()),
                ('locale', models.CharField(default='pt-BR', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_scenario_playbooks', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_scenario_playbooks',
                'ordering': ('scenario_key', 'playbook_code'),
            },
        ),
        migrations.CreateModel(
            name='Client360SuggestedActionDismissal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_key', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_action_dismissals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_action_dismissals', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_action_dismissals', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_suggested_action_dismissals',
            },
        ),
        migrations.CreateModel(
            name='Client360QbrDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quarter_key', models.CharField(max_length=16)),
                ('content_md', models.TextField(blank=True, default='')),
                ('human_edited_md', models.TextField(blank=True, default='')),
                ('source_facts_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_qbr_drafts', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_qbr_drafts', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_qbr_drafts',
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceclient360weeklybriefing',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'period_start'), name='client360_weekly_briefing_ws_week_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workspaceclient360scenarioplaybook',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'scenario_key', 'locale'), name='client360_scenario_playbook_uniq'),
        ),
        migrations.AddConstraint(
            model_name='client360suggestedactiondismissal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'member', 'action_key'), name='client360_action_dismiss_uniq'),
        ),
        migrations.AddConstraint(
            model_name='client360qbrdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'quarter_key'), name='client360_qbr_draft_project_quarter_uniq'),
        ),
    ]
