export type TInstanceAIConfigurationKeys =
  | "LLM_API_KEY"
  | "LLM_MODEL"
  | "LLM_PROVIDER"
  | "LLM_BASE_URL"
  | "ASSISTANT_ENABLED"
  | "ASSISTANT_MAX_MESSAGES_PER_USER_PER_HOUR"
  | "ASSISTANT_MAX_MESSAGES_PER_WORKSPACE_PER_HOUR"
  | "ASSISTANT_MAX_TOOL_ROUNDS"
  | "VITE_ENABLE_OPEROZ_ASSISTANT";
