from django.urls import path

from operis.app.views import (
    BoardCustomFieldBulkAddEndpoint,
    BoardCustomFieldDetailEndpoint,
    BoardCustomFieldEndpoint,
    BoardIssueTypeDetailEndpoint,
    BoardIssueTypeEndpoint,
    BoardIssuesViewSet,
    BoardMemberDetailEndpoint,
    BoardMemberEndpoint,
    BoardClient360ViewSet,
    BoardMetaViewSet,
    BoardModulesViewSet,
    BoardPermissionCatalogEndpoint,
    BoardProjectFieldLayoutDetailEndpoint,
    BoardProjectFieldLayoutEndpoint,
    BoardProjectFormLayoutEndpoint,
    BoardRoleDetailEndpoint,
    BoardRoleDuplicateEndpoint,
    BoardRoleEndpoint,
    BoardStatusReportDetailEndpoint,
    BoardStatusReportEndpoint,
    BoardStatusReportExportEndpoint,
    BoardViewSet,
    WorkspaceCustomFieldDetailEndpoint,
    WorkspaceCustomFieldEndpoint,
)

urlpatterns = [
    path(
        "workspaces/<str:slug>/boards/",
        BoardViewSet.as_view({"get": "list", "post": "create"}),
        name="workspace-boards",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/",
        BoardViewSet.as_view({"get": "retrieve", "patch": "partial_update", "delete": "destroy"}),
        name="workspace-board",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/archive/",
        BoardViewSet.as_view({"post": "archive"}),
        name="workspace-board-archive",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/unarchive/",
        BoardViewSet.as_view({"post": "unarchive"}),
        name="workspace-board-unarchive",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/issues/",
        BoardIssuesViewSet.as_view({"get": "list"}),
        name="workspace-board-issues",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/meta/",
        BoardMetaViewSet.as_view({"get": "retrieve"}),
        name="workspace-board-meta",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/client-360/",
        BoardClient360ViewSet.as_view({"get": "list"}),
        name="workspace-board-client-360",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/client-360/<uuid:project_id>/",
        BoardClient360ViewSet.as_view({"get": "retrieve"}),
        name="workspace-board-client-360-detail",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/modules/",
        BoardModulesViewSet.as_view({"get": "list"}),
        name="workspace-board-modules",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/issue-types/",
        BoardIssueTypeEndpoint.as_view(),
        name="workspace-board-issue-types",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/issue-types/<uuid:pk>/",
        BoardIssueTypeDetailEndpoint.as_view(),
        name="workspace-board-issue-type",
    ),
    path(
        "workspaces/<str:slug>/custom-fields/",
        WorkspaceCustomFieldEndpoint.as_view(),
        name="workspace-custom-fields",
    ),
    path(
        "workspaces/<str:slug>/custom-fields/<uuid:pk>/",
        WorkspaceCustomFieldDetailEndpoint.as_view(),
        name="workspace-custom-field",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/custom-fields/",
        BoardCustomFieldEndpoint.as_view(),
        name="workspace-board-custom-fields",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/custom-fields/bulk-add/",
        BoardCustomFieldBulkAddEndpoint.as_view(),
        name="workspace-board-custom-fields-bulk",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/custom-fields/<uuid:pk>/",
        BoardCustomFieldDetailEndpoint.as_view(),
        name="workspace-board-custom-field",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/project-field-layout/",
        BoardProjectFieldLayoutEndpoint.as_view(),
        name="workspace-board-project-field-layout",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/project-field-layout/<uuid:pk>/",
        BoardProjectFieldLayoutDetailEndpoint.as_view(),
        name="workspace-board-project-field-layout-detail",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/project-form-layout/",
        BoardProjectFormLayoutEndpoint.as_view(),
        name="workspace-board-project-form-layout",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/permission-catalog/",
        BoardPermissionCatalogEndpoint.as_view(),
        name="workspace-board-permission-catalog",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/roles/",
        BoardRoleEndpoint.as_view(),
        name="workspace-board-roles",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/roles/<uuid:pk>/",
        BoardRoleDetailEndpoint.as_view(),
        name="workspace-board-role",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/roles/<uuid:pk>/duplicate/",
        BoardRoleDuplicateEndpoint.as_view(),
        name="workspace-board-role-duplicate",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/members/",
        BoardMemberEndpoint.as_view(),
        name="workspace-board-members",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/members/<uuid:user_id>/",
        BoardMemberDetailEndpoint.as_view(),
        name="workspace-board-member",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/status-reports/",
        BoardStatusReportEndpoint.as_view(),
        name="workspace-board-status-reports",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/status-reports/<uuid:pk>/",
        BoardStatusReportDetailEndpoint.as_view(),
        name="workspace-board-status-report",
    ),
    path(
        "workspaces/<str:slug>/boards/<str:board_slug>/status-reports/<uuid:pk>/export/",
        BoardStatusReportExportEndpoint.as_view(),
        name="workspace-board-status-report-export",
    ),
]
