import { op } from "./types.js";

const ws = "workspace_slug";

export const APP_WORKSPACE_OPERATIONS = [
  op("workspaces", "operis_check_workspace_slug", "Verifica slug disponível", "app", "GET", "/workspace-slug-check/", []),
  op("workspaces", "operis_list_workspaces", "Lista workspaces", "app", "GET", "/workspaces/", []),
  op("workspaces", "operis_create_workspace", "Cria workspace", "app", "POST", "/workspaces/", [], { body: true }),
  op("workspaces", "operis_get_workspace", "Detalhe workspace", "app", "GET", `/workspaces/{${ws}}/`, [ws]),
  op("workspaces", "operis_update_workspace", "Atualiza workspace", "app", "PATCH", `/workspaces/{${ws}}/`, [ws], { body: true }),
  op("workspaces", "operis_delete_workspace", "Remove workspace", "app", "DELETE", `/workspaces/{${ws}}/`, [ws]),
  op("workspaces", "operis_list_my_workspaces", "Meus workspaces", "app", "GET", "/users/me/workspaces/", []),
  op("workspaces", "operis_list_workspace_invitations", "Convites workspace", "app", "GET", `/workspaces/{${ws}}/invitations/`, [ws]),
  op("workspaces", "operis_create_workspace_invitation", "Cria convite", "app", "POST", `/workspaces/{${ws}}/invitations/`, [ws], { body: true }),
  op("workspaces", "operis_get_workspace_invitation", "Detalhe convite", "app", "GET", `/workspaces/{${ws}}/invitations/{pk}/`, [ws, "pk"]),
  op("workspaces", "operis_update_workspace_invitation", "Atualiza convite", "app", "PATCH", `/workspaces/{${ws}}/invitations/{pk}/`, [ws, "pk"], {
    body: true,
  }),
  op("workspaces", "operis_delete_workspace_invitation", "Remove convite", "app", "DELETE", `/workspaces/{${ws}}/invitations/{pk}/`, [ws, "pk"]),
  op("workspaces", "operis_join_workspace", "Aceita convite", "app", "POST", `/workspaces/{${ws}}/invitations/{pk}/join/`, [ws, "pk"], { body: true }),
  op("workspaces", "operis_list_my_workspace_invitations", "Meus convites", "app", "GET", "/users/me/workspaces/invitations/", []),
  op("workspaces", "operis_list_workspace_members_app", "Membros (app)", "app", "GET", `/workspaces/{${ws}}/members/`, [ws]),
  op("workspaces", "operis_get_workspace_member", "Detalhe membro", "app", "GET", `/workspaces/{${ws}}/members/{pk}/`, [ws, "pk"]),
  op("workspaces", "operis_update_workspace_member", "Atualiza membro", "app", "PATCH", `/workspaces/{${ws}}/members/{pk}/`, [ws, "pk"], { body: true }),
  op("workspaces", "operis_remove_workspace_member", "Remove membro", "app", "DELETE", `/workspaces/{${ws}}/members/{pk}/`, [ws, "pk"]),
  op("workspaces", "operis_leave_workspace", "Sair do workspace", "app", "POST", `/workspaces/{${ws}}/members/leave/`, [ws], { body: true }),
  op("workspaces", "operis_list_project_members_workspace", "Membros de projetos", "app", "GET", `/workspaces/{${ws}}/project-members/`, [ws]),
  op("workspaces", "operis_get_workspace_labels", "Labels workspace", "app", "GET", `/workspaces/{${ws}}/labels/`, [ws]),
  op("workspaces", "operis_get_workspace_states", "Estados workspace", "app", "GET", `/workspaces/{${ws}}/states/`, [ws]),
  op("workspaces", "operis_get_workspace_estimates", "Estimativas workspace", "app", "GET", `/workspaces/{${ws}}/estimates/`, [ws]),
  op("workspaces", "operis_get_workspace_modules", "Módulos workspace", "app", "GET", `/workspaces/{${ws}}/modules/`, [ws]),
  op("workspaces", "operis_get_workspace_cycles", "Ciclos workspace", "app", "GET", `/workspaces/{${ws}}/cycles/`, [ws]),
  op("workspaces", "operis_list_user_favorites", "Favoritos", "app", "GET", `/workspaces/{${ws}}/user-favorites/`, [ws]),
  op("workspaces", "operis_create_user_favorite", "Adiciona favorito", "app", "POST", `/workspaces/{${ws}}/user-favorites/`, [ws], { body: true }),
  op("workspaces", "operis_update_user_favorite", "Atualiza favorito", "app", "PATCH", `/workspaces/{${ws}}/user-favorites/{favorite_id}/`, [ws, "favorite_id"], {
    body: true,
  }),
  op("workspaces", "operis_delete_user_favorite", "Remove favorito", "app", "DELETE", `/workspaces/{${ws}}/user-favorites/{favorite_id}/`, [ws, "favorite_id"]),
  op("workspaces", "operis_get_home_preferences", "Preferências home", "app", "GET", `/workspaces/{${ws}}/home-preferences/`, [ws]),
  op("workspaces", "operis_update_home_preferences", "Atualiza home", "app", "PATCH", `/workspaces/{${ws}}/home-preferences/`, [ws], { body: true }),
  op("workspaces", "operis_get_recent_visits", "Visitas recentes", "app", "GET", `/workspaces/{${ws}}/recent-visits/`, [ws]),
  op("workspaces", "operis_get_sidebar_preferences", "Sidebar", "app", "GET", `/workspaces/{${ws}}/sidebar-preferences/`, [ws]),
  op("workspaces", "operis_update_sidebar_preferences", "Atualiza sidebar", "app", "PATCH", `/workspaces/{${ws}}/sidebar-preferences/`, [ws], { body: true }),
  op("workspaces", "operis_list_quick_links", "Quick links", "app", "GET", `/workspaces/{${ws}}/quick-links/`, [ws]),
  op("workspaces", "operis_create_quick_link", "Cria quick link", "app", "POST", `/workspaces/{${ws}}/quick-links/`, [ws], { body: true }),
  op("workspaces", "operis_update_quick_link", "Atualiza quick link", "app", "PATCH", `/workspaces/{${ws}}/quick-links/{pk}/`, [ws, "pk"], { body: true }),
  op("workspaces", "operis_delete_quick_link", "Remove quick link", "app", "DELETE", `/workspaces/{${ws}}/quick-links/{pk}/`, [ws, "pk"]),
  op("workspaces", "operis_list_draft_issues", "Rascunhos de issues", "app", "GET", `/workspaces/{${ws}}/draft-issues/`, [ws]),
  op("workspaces", "operis_create_draft_issue", "Cria rascunho", "app", "POST", `/workspaces/{${ws}}/draft-issues/`, [ws], { body: true }),
  op("workspaces", "operis_update_draft_issue", "Atualiza rascunho", "app", "PATCH", `/workspaces/{${ws}}/draft-issues/{pk}/`, [ws, "pk"], { body: true }),
  op("workspaces", "operis_delete_draft_issue", "Remove rascunho", "app", "DELETE", `/workspaces/{${ws}}/draft-issues/{pk}/`, [ws, "pk"]),
  op("workspaces", "operis_draft_to_issue", "Converte rascunho em issue", "app", "POST", `/workspaces/{${ws}}/draft-to-issue/{draft_id}/`, [ws, "draft_id"], {
    body: true,
  }),
  op("workspaces", "operis_export_issues", "Exporta issues", "app", "POST", `/workspaces/{${ws}}/export-issues/`, [ws], { body: true }),
];
