# Generated by Django 4.2.30 on 2026-06-14 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0170_client360_operational'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client360ConsultantAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('period_month', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'client_360_consultant_allocations',
                'ordering': ('-period_month', 'project_id', 'member_id'),
            },
        ),
        migrations.CreateModel(
            name='Client360HarnessCostLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pipeline_id', models.CharField(max_length=120)),
                ('cost_usd', models.DecimalField(decimal_places=4, max_digits=14)),
                ('attributed_month', models.DateField()),
                ('attribution_tags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'client_360_harness_cost_line_items',
                'ordering': ('-attributed_month', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Client360ProjectFinopsProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('period_month', models.DateField(help_text='First day of the month for this snapshot.')),
                ('hours_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacity_hours', models.DecimalField(decimal_places=2, default=160, max_digits=10)),
                ('harness_cost_mtd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('harness_cost_breakdown', models.JSONField(blank=True, default=list)),
                ('harness_project_tag', models.CharField(blank=True, default='', max_length=120)),
                ('harness_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('budget_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('revenue_contract', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'client_360_project_finops_profiles',
                'ordering': ('-period_month', 'project_id'),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceClient360FinopsSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('variance_alert_pct', models.PositiveSmallIntegerField(default=10)),
                ('margin_alert_pct', models.PositiveSmallIntegerField(default=15)),
                ('squad_weekly_capacity_hours', models.PositiveSmallIntegerField(default=40)),
            ],
            options={
                'db_table': 'workspace_client_360_finops_settings',
            },
        ),
        migrations.RemoveIndex(
            model_name='boardstatusreport',
            name='board_sr_proj_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='boardstatusreport',
            name='board_sr_proj_module_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationdeadletter',
            new_name='board_autom_board_i_98b964_idx',
            old_name='board_auto_dlq_board_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationdeadletter',
            new_name='board_autom_workspa_462203_idx',
            old_name='board_auto_dlq_workspace_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationemailtemplate',
            new_name='board_autom_board_i_0d79bf_idx',
            old_name='board_auto_email_tpl_board_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationhook',
            new_name='board_autom_board_i_b7ef62_idx',
            old_name='board_auto_hook_board_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationhook',
            new_name='board_autom_workspa_1e7587_idx',
            old_name='board_auto_hook_ws_board_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationoutbox',
            new_name='board_autom_status_9b2f65_idx',
            old_name='board_auto_outbox_status_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationoutbox',
            new_name='board_autom_board_i_4c941f_idx',
            old_name='board_auto_outbox_board_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationpackinstall',
            new_name='board_autom_board_i_a36ebc_idx',
            old_name='board_auto_pack_board_name_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationpackinstall',
            new_name='board_autom_workspa_c943c7_idx',
            old_name='board_auto_pack_ws_board_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationpublishaudit',
            new_name='board_autom_board_i_2d06a8_idx',
            old_name='board_auto_pub_board_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationpublishaudit',
            new_name='board_autom_rule_id_04c3cc_idx',
            old_name='board_auto_pub_rule_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrule',
            new_name='board_autom_board_i_570df4_idx',
            old_name='board_auto_rule_board_en_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrule',
            new_name='board_autom_workspa_d2f35d_idx',
            old_name='board_auto_rule_ws_board_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrule',
            new_name='board_autom_board_i_39a5e3_idx',
            old_name='board_auto_board_i_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrulerevision',
            new_name='board_autom_rule_id_de2d5f_idx',
            old_name='board_auto_rule_c_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrulerevision',
            new_name='board_autom_board_i_946e01_idx',
            old_name='board_auto_board_k_c_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrun',
            new_name='board_autom_board_i_27e657_idx',
            old_name='board_auto_run_board_st_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationrun',
            new_name='board_autom_rule_id_d45547_idx',
            old_name='board_auto_run_rule_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='boardautomationscript',
            new_name='board_autom_board_i_38656b_idx',
            old_name='board_auto_script_board_idx',
        ),
        migrations.RenameIndex(
            model_name='boardplaybook',
            new_name='board_playb_board_i_72fec4_idx',
            old_name='board_playb_board_i_6f0a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='boardplaybook',
            new_name='board_playb_workspa_b10618_idx',
            old_name='board_playb_workspa_91c4e1_idx',
        ),
        migrations.RenameIndex(
            model_name='boardstatusreport',
            new_name='board_statu_board_i_d84d13_idx',
            old_name='board_sr_board_period_idx',
        ),
        migrations.RenameIndex(
            model_name='boardstatusreport',
            new_name='board_statu_workspa_c8f60b_idx',
            old_name='board_sr_ws_board_idx',
        ),
        migrations.RenameIndex(
            model_name='client360healthsnapshot',
            new_name='client_360__project_05f1bd_idx',
            old_name='client360_hs_proj_week_idx',
        ),
        migrations.RenameIndex(
            model_name='client360healthsnapshot',
            new_name='client_360__workspa_514da8_idx',
            old_name='client360_hs_ws_week_idx',
        ),
        migrations.RenameIndex(
            model_name='client360qbrguestlink',
            new_name='client_360__workspa_f7c2f3_idx',
            old_name='client360_qbr_guest_ws_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='client360qbrguestlink',
            new_name='client_360__expires_43ea6c_idx',
            old_name='client360_qbr_guest_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='client360statusreportreminderlog',
            new_name='client_360__board_i_92e72b_idx',
            old_name='client360_sr_rem_log_board_idx',
        ),
        migrations.AddField(
            model_name='boardautomationpackinstall',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='boardautomationpackinstall',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='assistantchatjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='assistantchatjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='assistantchatjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='assistantchatjob',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='assistantchatjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='assistantchatjob',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='boardautomationpackinstall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='boardautomationpackinstall',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='boardautomationpackinstall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='boardclient360intaketype',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='boardclient360intaketype',
            name='type_name_pattern',
            field=models.CharField(blank=True, default='', help_text='Case-insensitive substring match on issue type name; empty matches intake/entrada defaults.', max_length=120),
        ),
        migrations.AlterField(
            model_name='boardcustomfield',
            name='form_span',
            field=models.CharField(choices=[('half', 'Half width'), ('full', 'Full width')], default='half', max_length=8),
        ),
        migrations.AlterField(
            model_name='boardplaybook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='boardplaybook',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='boardplaybook',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='boardprojectfieldlayout',
            name='standard_field_key',
            field=models.CharField(blank=True, choices=[('name', 'Name'), ('identifier', 'Identifier'), ('description', 'Description'), ('project_lead', 'Project lead'), ('responsible_stakeholder', 'Responsible stakeholder'), ('default_assignee', 'Default assignee'), ('network', 'Network'), ('timezone', 'Timezone')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='boardstandardfield',
            name='form_span',
            field=models.CharField(choices=[('half', 'Half width'), ('full', 'Full width')], default='half', max_length=8),
        ),
        migrations.AlterField(
            model_name='boardstatusreport',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='db.module'),
        ),
        migrations.AlterField(
            model_name='boardstatusreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='db.project'),
        ),
        migrations.AlterField(
            model_name='client360workspacesharedview',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projectcustomfieldvalue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AlterField(
            model_name='projectcustomfieldvalue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AlterField(
            model_name='workspaceclient360settings',
            name='health_score_display_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, Visão 360 UI shows numeric health score alongside RAG semáforo.'),
        ),
        migrations.AlterField(
            model_name='workspacejiraopsconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='workspacejiraopsconfig',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workspaceclient360finopssettings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workspaceclient360finopssettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workspaceclient360finopssettings',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_finops_settings', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='client360projectfinopsprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='client360projectfinopsprofile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_finops_profiles', to='db.project'),
        ),
        migrations.AddField(
            model_name='client360projectfinopsprofile',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='client360projectfinopsprofile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_finops_profiles', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='client360harnesscostlineitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='client360harnesscostlineitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_360_harness_cost_lines', to='db.project'),
        ),
        migrations.AddField(
            model_name='client360harnesscostlineitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='client360harnesscostlineitem',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_harness_cost_lines', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='client360consultantallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='client360consultantallocation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_consultant_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client360consultantallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_consultant_allocations', to='db.project'),
        ),
        migrations.AddField(
            model_name='client360consultantallocation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='client360consultantallocation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_consultant_allocations', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='client360projectfinopsprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'period_month'), name='client360_finops_profile_unique_month'),
        ),
        migrations.AddConstraint(
            model_name='client360harnesscostlineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'pipeline_id', 'attributed_month'), name='client360_harness_cost_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='client360consultantallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'member', 'period_month'), name='client360_consultant_alloc_unique_month'),
        ),
    ]
