# Generated by Django 4.2.30 on 2026-06-14 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operoz.db.models.client_360_webhook_subscription
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0172_client360_intelligence'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceClient360EnterpriseSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phase_flags', models.JSONField(blank=True, default=dict)),
                ('list_grouping_mode', models.CharField(choices=[('project', 'Project'), ('customer', 'Customer')], default='project', max_length=16)),
                ('crm_enabled', models.BooleanField(default=False)),
                ('crm_provider', models.CharField(blank=True, default='', max_length=32)),
                ('crm_config', models.JSONField(blank=True, default=dict)),
                ('crm_push_enabled', models.BooleanField(default=False)),
                ('crm_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('crm_stale', models.BooleanField(default=False)),
                ('retention_weeks', models.PositiveSmallIntegerField(default=52)),
                ('data_region', models.CharField(default='EU', max_length=8)),
                ('bi_export_enabled', models.BooleanField(default=True)),
                ('guest_sso_enabled', models.BooleanField(default=False)),
                ('guest_sso_config', models.JSONField(blank=True, default=dict)),
                ('guest_magic_link_fallback', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_enterprise_settings', to='db.workspace')),
            ],
            options={
                'db_table': 'workspace_client_360_enterprise_settings',
            },
        ),
        migrations.CreateModel(
            name='Client360WebhookSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(max_length=512)),
                ('secret', models.CharField(default=operoz.db.models.client_360_webhook_subscription.generate_webhook_secret, max_length=128)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_webhook_subscriptions', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_webhook_subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Client360WebhookDeliveryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='db.client360webhooksubscription')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'client_360_webhook_delivery_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Client360Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('external_crm_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('segment', models.CharField(blank=True, default='', max_length=64)),
                ('account_owner', models.CharField(blank=True, default='', max_length=255)),
                ('revenue_contract', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('logo_props', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_customers', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_customers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client360CrmSyncRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('failed', 'Failed')], max_length=16)),
                ('customers_updated', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_crm_sync_runs', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_crm_sync_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Client360AuditEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_360_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_360_audit_entries', to='db.workspace')),
            ],
            options={
                'db_table': 'client_360_audit_entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='client360_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='db.client360customer'),
        ),
        migrations.AddConstraint(
            model_name='client360customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('external_crm_id', ''), _negated=True)), fields=('workspace', 'external_crm_id'), name='client360_customer_crm_id_uniq'),
        ),
        migrations.AddIndex(
            model_name='client360auditentry',
            index=models.Index(fields=['workspace', 'entity_type', '-created_at'], name='client_360__workspa_02c5f5_idx'),
        ),
    ]
