# Generated by Django 4.2.30 on 2026-08-29 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operoz.db.models.alert
import operoz.db.models.notification
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0202_drop_client_360"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alertlog",
            new_name="alert_logs_issue_i_252eba_idx",
            old_name="alert_logs_issue_a_idx",
        ),
        migrations.RenameIndex(
            model_name="alertlog",
            new_name="alert_logs_receive_c642f1_idx",
            old_name="alert_logs_receive_idx",
        ),
        migrations.RenameIndex(
            model_name="alertlog",
            new_name="alert_logs_workspa_cb57ce_idx",
            old_name="alert_logs_workspa_idx",
        ),
        migrations.RenameIndex(
            model_name="alertlog",
            new_name="alert_logs_receive_54c651_idx",
            old_name="alert_log_dedup_idx",
        ),
        migrations.RenameIndex(
            model_name="alertrule",
            new_name="alert_rules_workspa_2ec5ef_idx",
            old_name="alert_rules_workspa_idx",
        ),
        migrations.RenameIndex(
            model_name="boardintakeform",
            new_name="board_intak_board_i_7231ec_idx",
            old_name="board_intake_board_pub_idx",
        ),
        migrations.RenameIndex(
            model_name="boardintakeform",
            new_name="board_intak_workspa_ff43e1_idx",
            old_name="board_intake_ws_board_idx",
        ),
        migrations.RenameIndex(
            model_name="boardsupportqueue",
            new_name="board_suppo_board_i_c44601_idx",
            old_name="board_supp_queue_board_sort_idx",
        ),
        migrations.RenameIndex(
            model_name="boardsupportqueue",
            new_name="board_suppo_workspa_785e85_idx",
            old_name="board_supp_queue_ws_board_idx",
        ),
        migrations.RenameIndex(
            model_name="boardsupportslapolicy",
            new_name="board_suppo_workspa_699d99_idx",
            old_name="board_sla_policy_ws_board_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewcomment",
            new_name="page_review_session_ee01ee_idx",
            old_name="page_review_session_7f3ac2_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewcomment",
            new_name="page_review_session_9ae7f3_idx",
            old_name="page_review_session_1e4b55_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewevent",
            new_name="page_review_session_372484_idx",
            old_name="page_review_session_9aa0de_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewinvite",
            new_name="page_review_session_db9a04_idx",
            old_name="page_review_session_2d8e11_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewinvite",
            new_name="page_review_expires_9cefc5_idx",
            old_name="page_review_expires_91bc02_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewsession",
            new_name="page_review_page_id_096b0e_idx",
            old_name="page_review_page_id_8a2f1d_idx",
        ),
        migrations.RenameIndex(
            model_name="pagereviewsession",
            new_name="page_review_workspa_60670e_idx",
            old_name="page_review_workspa_4c91ab_idx",
        ),
        migrations.RenameIndex(
            model_name="workflow",
            new_name="workflows_workspa_4e3fa6_idx",
            old_name="idx_workflow_workspace_active",
        ),
        migrations.RenameIndex(
            model_name="workflow",
            new_name="workflows_workspa_1d0bb0_idx",
            old_name="idx_workflow_workspace_draft",
        ),
        migrations.RenameIndex(
            model_name="workflowtransition",
            new_name="workflow_tr_workflo_bbb9e4_idx",
            old_name="idx_transition_workflow_from_state",
        ),
        migrations.RenameIndex(
            model_name="workflowtransition",
            new_name="workflow_tr_workflo_b2ae67_idx",
            old_name="idx_transition_workflow_global",
        ),
        migrations.AlterField(
            model_name="alertlog",
            name="alert_type",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="alertlog",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("issue_created", "Issue Created"),
                    ("due_date_approaching", "Due Date Approaching"),
                    ("due_date_overdue", "Due Date Overdue"),
                    ("missing_due_date", "Missing Due Date"),
                    ("state_change", "State Change"),
                    ("assignee_change", "Assignee Change"),
                    ("intake_created", "Intake Created"),
                    ("support_ticket_created", "Support Ticket Created"),
                    ("support_ticket_accepted", "Support Ticket Accepted"),
                    ("support_sla_approaching", "Support SLA Approaching"),
                    ("support_sla_breached", "Support SLA Breached"),
                    ("support_ticket_closed", "Support Ticket Closed"),
                    ("support_no_team_response", "Support No Team Response"),
                    ("issue_no_activity", "Issue No Activity"),
                    ("in_progress_too_long", "In Progress Too Long"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="channels",
            field=models.JSONField(default=operoz.db.models.alert.default_alert_rule_channels),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="boardintakeform",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="boardintakeform",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
        ),
        migrations.AlterField(
            model_name="boardintakeform",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="boardintakeform",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="boardsupportqueue",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="boardsupportqueue",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="boardsupportslapolicy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="boardsupportslapolicy",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="intakeissue",
            name="status",
            field=models.IntegerField(
                choices=[
                    (-2, "Pending"),
                    (-1, "Rejected"),
                    (0, "Snoozed"),
                    (1, "Accepted"),
                    (2, "Duplicate"),
                    (3, "Closed"),
                ],
                default=-2,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="workflow_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="db.workflowscheme",
            ),
        ),
        migrations.AlterField(
            model_name="transitioncondition",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="transitioncondition",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transitioncondition",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="transitionpostfunction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="transitionpostfunction",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transitionpostfunction",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="transitionscreen",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="transitionscreen",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transitionscreen",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="transitionvalidator",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="transitionvalidator",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transitionvalidator",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="useralertpreference",
            name="alert_type",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="channels",
            field=models.JSONField(default=operoz.db.models.notification.default_alert_channels),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="workflowscheme",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="workflowscheme",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowscheme",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="workflowschemeentry",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="workflowschemeentry",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowschemeentry",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowtransition",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="workspacejiraopsconfig",
            name="board_slug",
            field=models.CharField(default="squad-as-a-service", max_length=48),
        ),
    ]
